global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'fastapi_app'
    static_configs:
      - targets: ['host.docker.internal:8000']

  - job_name: "node"
    static_configs:
      - targets: [ "node_exporter:9100" ]
